- sghPage.txt
> 추가 sghPage.txt

- usedArticleTrade/src/main/webapp/WEB-INF/.gitignore
- usedArticleTrade/src/main/webapp/index.jsp
- usedArticleTrade/src/main/webapp/views/FAQ/mainFAQ.jsp
- usedArticleTrade/src/main/webapp/views/FAQ/myFAQ.jsp
- usedArticleTrade/src/main/webapp/views/FAQ/writeFAQ.jsp
- usedArticleTrade/src/main/webapp/views/board/boardIndex.jsp
- usedArticleTrade/src/main/webapp/views/board/boardPost.jsp
- usedArticleTrade/src/main/webapp/views/board/boardWrite.jsp
- usedArticleTrade/src/main/webapp/views/category/mainPart.jsp
- usedArticleTrade/src/main/webapp/views/login/login.jsp
- usedArticleTrade/src/main/webapp/views/myPage/heart.jsp
- usedArticleTrade/src/main/webapp/views/myPage/myComment.jsp
- usedArticleTrade/src/main/webapp/views/myPage/profile.jsp
- usedArticleTrade/src/main/webapp/views/myPage/salesPost.jsp
- usedArticleTrade/src/main/webapp/views/posting/postPage.jsp
- usedArticleTrade/src/main/webapp/views/posting/postingProduct.jsp
> feat 폴더구조추가

- usedArticleTrade/src/main/webapp/views/myPage/heart.jsp
- usedArticleTrade/src/main/webapp/views/myPage/myComment.jsp
- usedArticleTrade/src/main/webapp/views/myPage/profile.jsp
- usedArticleTrade/src/main/webapp/views/myPage/salesPost.jsp
> feat_마이페이지_댓글,찜목록,판매글ui추가

- usedArticleTrade/src/main/webapp/views/myPage/profile.jsp
- usedArticleTrade/src/main/webapp/views/myPage/salesPost.jsp
> edit_마이페이지_판매글,나의정보 ui수정

- usedArticleTrade/.classpath
- usedArticleTrade/src/main/webapp/views/myPage/heart.jsp
- usedArticleTrade/src/main/webapp/views/myPage/myComment.jsp
- usedArticleTrade/src/main/webapp/views/myPage/profile.jsp
- usedArticleTrade/src/main/webapp/views/myPage/salesPost.jsp
> edit_마이페이지_ui완성

- src/main/webapp/views/FAQ/mainFAQ.jsp
- src/main/webapp/views/FAQ/writeFAQ.jsp
- src/main/webapp/views/common/header.jsp
- src/main/webapp/views/login/login.jsp
- src/main/webapp/views/login/signIn.jsp
FAQ, LOGIN 뷰
width, contextpath, include 수정
> FAQ 로그인 와이드,이미지경로,인클루드 수정

- resources/mappers/product-mapper.xml
- resources/mybatis-config.xml
- src/main/java/com/two/common/Template.java
- src/main/java/com/two/product/controller/ProductListController.java
- src/main/java/com/two/product/model/dao/ProductDao.java
- src/main/java/com/two/product/service/ProductServiceImpl.java
- src/main/webapp/index.jsp
> [김도헌] index.jsp 개발중(현재 오류뜸)

- src/main/java/com/two/product/controller/ProductInsertController.java
- src/main/java/com/two/product/model/vo/Product.java
> [임병준] product 충돌나서 두개 생긴거 수정

- src/main/java/com/two/myPage/controller/CheckPasswordController.java
- src/main/java/com/two/myPage/controller/IndexToMyPageController.java
- src/main/java/com/two/myPage/controller/IndexToProfileController.java
- src/main/java/com/two/myPage/model/dao/MyPageDao.java
- src/main/java/com/two/myPage/service/MyPageService.java
- src/main/java/com/two/myPage/service/MyPageServiceImpl.java
- src/main/webapp/views/myPage/myPageMain.jsp
- src/main/webapp/views/myPage/profile.jsp
> [이원기] 마이페이지 회원정보 가져오기

- resources/mappers/board-mapper.xml
- resources/mappers/member-mapper.xml
- src/main/java/com/two/myPage/controller/IndexToTradeHistory.java
- src/main/java/com/two/myPage/model/dao/MyPageDao.java
- src/main/java/com/two/myPage/service/MyPageService.java
- src/main/java/com/two/myPage/service/MyPageServiceImpl.java
- src/main/webapp/views/myPage/profile.jsp
- src/main/webapp/views/myPage/salesPost.jsp
> [이원기] 판매글 리스트 불러오기

- src/main/java/com/two/common/Template.java
- src/main/java/com/two/faq/model/dao/FaqDao.java
- src/main/java/com/two/myPage/model/dao/MyPageDao.java
- src/main/webapp/style/idFind.css
- src/main/webapp/views/login/idFind.jsp
> [심규홍] id 찾기 css jsp추가

- resources/mappers/member-mapper.xml
- resources/mappers/member-mapper.xml.rej
- src/main/java/com/two/member/controller/MemberIdFindController.java
- src/main/java/com/two/member/model/dao/MemberDao.java
- src/main/java/com/two/member/service/MemberService.java
- src/main/java/com/two/product/model/dao/ProductDao.java
> [심규홍] 아이디 찾기 기능 추가(수정 필요)

- resources/mappers/member-mapper.xml
- src/main/java/com/two/member/controller/MemberPwdFindController.java
- src/main/java/com/two/member/model/dao/MemberDao.java
- src/main/java/com/two/member/model/vo/Member.java
- src/main/java/com/two/member/service/MemberService.java
- src/main/webapp/style/pwdFind.css
- src/main/webapp/views/login/idFind.jsp
- src/main/webapp/views/login/login.jsp
- src/main/webapp/views/login/pwdFind.jsp
id, pwd 찾기 구현 완료
멤버 > 컨트롤러 > idFind, pwFind 추가
멤버 > 다오 > dao 수정
멤버 > 서비스 > service 수정
리소스 > 매퍼스 > 멤버 매퍼 수정
웹앱 > 뷰스 > 로그인 > id, pwd find / login jsp 수정  pwdFind css 수정
> [심규홍] ID, PWD 찾기 기능 구현 완료

- src/main/java/com/two/member/controller/MemberIdFindController.java
- src/main/java/com/two/member/controller/MemberPwdFindController.java
- src/main/webapp/style/FindResult.css
- src/main/webapp/views/common/FindResult.jsp
아이디 / 비밀번호 찾기 결과창 추가
id, pwd 찾기 결과창 추가
idfind, pwdfind 컨트롤러 수정
뷰스 > 커몬 > findresult jsp/css 추가
> [심규홍] 아이디/비밀번호 찾기 결과창 추가

- resources/mappers/product-mapper.xml
- src/main/java/com/two/product/controller/ProductCategorySearch.java
- src/main/java/com/two/product/model/dao/ProductDao.java
- src/main/java/com/two/product/service/ProductService.java
- src/main/java/com/two/product/service/ProductServiceImpl.java
- src/main/webapp/script/index.js
- src/main/webapp/style/mainPart.css
- src/main/webapp/views/category/mainPart.jsp
- src/main/webapp/views/common/header.jsp
> [김도헌] category 기능 추가

- resources/mappers/product-mapper.xml
- src/main/java/com/two/product/controller/ProductDeleteController.java
- src/main/java/com/two/product/controller/ProductInsertController.java
- src/main/java/com/two/product/model/dao/ProductDao.java
- src/main/java/com/two/product/service/ProductService.java
- src/main/java/com/two/product/service/ProductServiceImpl.java
- src/main/webapp/script/postPage.js
- src/main/webapp/style/postPage.css
- src/main/webapp/views/posting/postPage.jsp
[임병준] ProductDeleteController 구현, 댓글작성, 대댓글작성, 구매신청 ui 구현
> [임병준] ProductDeleteController 구현, 댓글작성, 대댓글작성, 구매신청 ui 구현

- src/main/java/com/two/member/controller/MemberLoginPageController.java
- src/main/webapp/views/FAQ/myFAQ.jsp
- src/main/webapp/views/common/errorPage.jsp
MemberLoginPageController, errorPage, myFAQ
> [심규홍] 한글 깨짐 수정

- resources/mappers/member-mapper.xml
- resources/mappers/myPage-mapper.xml
- src/main/java/com/two/myPage/controller/DeleteMemberController.java
- src/main/java/com/two/myPage/controller/DeleteMemberFormController.java
- src/main/java/com/two/myPage/controller/IndexToCommentHistory.java
- src/main/java/com/two/myPage/model/dao/MyPageDao.java
- src/main/java/com/two/myPage/service/MyPageService.java
- src/main/java/com/two/myPage/service/MyPageServiceImpl.java
- src/main/java/com/two/product/model/vo/Nreply.java
- src/main/java/com/two/product/model/vo/Reply.java
- src/main/webapp/views/myPage/deleteMember.jsp
- src/main/webapp/views/myPage/heart.jsp
- src/main/webapp/views/myPage/myComment.jsp
- src/main/webapp/views/myPage/myPageMain.jsp
- src/main/webapp/views/myPage/salesPost.jsp
[이원기] 회원탈퇴 기능 + 나의 댓글, 대댓글 목록 가져오기 날렸던거 복구 merge
> [이원기] 회원탈퇴 기능 + 나의 댓글, 대댓글 목록 가져오기 날렸던거 복구 merge

- src/main/java/com/two/product/model/vo/Nreply.java
- src/main/java/com/two/product/model/vo/Product.java
- src/main/java/com/two/product/model/vo/Reply.java
- src/main/java/com/two/product/model/vo/Request.java
> [임병준] sql Date 삭제

- src/main/webapp/views/myPage/myComment.jsp
- src/main/webapp/views/myPage/salesPost.jsp
> [이원기] 날짜 시간까지 뜨는거 안뜨게 수정merge
